/* 
 * Web of Science API Lite
 *
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Other
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OtherTests
    {
        // TODO uncomment below to declare an instance variable for Other
        //private Other instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Other
            //instance = new Other();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Other
        /// </summary>
        [Test]
        public void OtherInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Other
            //Assert.IsInstanceOfType<Other> (instance, "variable 'instance' is a Other");
        }


        /// <summary>
        /// Test the property 'IdentifierEissn'
        /// </summary>
        [Test]
        public void IdentifierEissnTest()
        {
            // TODO unit test for the property 'IdentifierEissn'
        }
        /// <summary>
        /// Test the property 'ContributorResearcherIDResearcherIDs'
        /// </summary>
        [Test]
        public void ContributorResearcherIDResearcherIDsTest()
        {
            // TODO unit test for the property 'ContributorResearcherIDResearcherIDs'
        }
        /// <summary>
        /// Test the property 'ContributorResearcherIDNames'
        /// </summary>
        [Test]
        public void ContributorResearcherIDNamesTest()
        {
            // TODO unit test for the property 'ContributorResearcherIDNames'
        }
        /// <summary>
        /// Test the property 'IdentifierDoi'
        /// </summary>
        [Test]
        public void IdentifierDoiTest()
        {
            // TODO unit test for the property 'IdentifierDoi'
        }
        /// <summary>
        /// Test the property 'IdentifierIssn'
        /// </summary>
        [Test]
        public void IdentifierIssnTest()
        {
            // TODO unit test for the property 'IdentifierIssn'
        }
        /// <summary>
        /// Test the property 'IdentifierArticleNo'
        /// </summary>
        [Test]
        public void IdentifierArticleNoTest()
        {
            // TODO unit test for the property 'IdentifierArticleNo'
        }
        /// <summary>
        /// Test the property 'IdentifierIsbn'
        /// </summary>
        [Test]
        public void IdentifierIsbnTest()
        {
            // TODO unit test for the property 'IdentifierIsbn'
        }
        /// <summary>
        /// Test the property 'ResearcherIDDisclaimer'
        /// </summary>
        [Test]
        public void ResearcherIDDisclaimerTest()
        {
            // TODO unit test for the property 'ResearcherIDDisclaimer'
        }
        /// <summary>
        /// Test the property 'IdentifierXrefDoi'
        /// </summary>
        [Test]
        public void IdentifierXrefDoiTest()
        {
            // TODO unit test for the property 'IdentifierXrefDoi'
        }
        /// <summary>
        /// Test the property 'IdentifierIds'
        /// </summary>
        [Test]
        public void IdentifierIdsTest()
        {
            // TODO unit test for the property 'IdentifierIds'
        }

    }

}
