/* 
 * Web of Science API Lite
 *
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Source
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SourceTests
    {
        // TODO uncomment below to declare an instance variable for Source
        //private Source instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Source
            //instance = new Source();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Source
        /// </summary>
        [Test]
        public void SourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Source
            //Assert.IsInstanceOfType<Source> (instance, "variable 'instance' is a Source");
        }


        /// <summary>
        /// Test the property 'Pages'
        /// </summary>
        [Test]
        public void PagesTest()
        {
            // TODO unit test for the property 'Pages'
        }
        /// <summary>
        /// Test the property 'SourceTitle'
        /// </summary>
        [Test]
        public void SourceTitleTest()
        {
            // TODO unit test for the property 'SourceTitle'
        }
        /// <summary>
        /// Test the property 'Issue'
        /// </summary>
        [Test]
        public void IssueTest()
        {
            // TODO unit test for the property 'Issue'
        }
        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Test]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
        /// <summary>
        /// Test the property 'SpecialIssue'
        /// </summary>
        [Test]
        public void SpecialIssueTest()
        {
            // TODO unit test for the property 'SpecialIssue'
        }
        /// <summary>
        /// Test the property 'BookSeriesTitle'
        /// </summary>
        [Test]
        public void BookSeriesTitleTest()
        {
            // TODO unit test for the property 'BookSeriesTitle'
        }
        /// <summary>
        /// Test the property 'PublishedBiblioDate'
        /// </summary>
        [Test]
        public void PublishedBiblioDateTest()
        {
            // TODO unit test for the property 'PublishedBiblioDate'
        }
        /// <summary>
        /// Test the property 'PublishedBiblioYear'
        /// </summary>
        [Test]
        public void PublishedBiblioYearTest()
        {
            // TODO unit test for the property 'PublishedBiblioYear'
        }

    }

}
