/* 
 * Web of Science API Lite
 *
 * A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WosLiteRecord
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WosLiteRecordTests
    {
        // TODO uncomment below to declare an instance variable for WosLiteRecord
        //private WosLiteRecord instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WosLiteRecord
            //instance = new WosLiteRecord();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WosLiteRecord
        /// </summary>
        [Test]
        public void WosLiteRecordInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WosLiteRecord
            //Assert.IsInstanceOfType<WosLiteRecord> (instance, "variable 'instance' is a WosLiteRecord");
        }


        /// <summary>
        /// Test the property 'UT'
        /// </summary>
        [Test]
        public void UTTest()
        {
            // TODO unit test for the property 'UT'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Doctype'
        /// </summary>
        [Test]
        public void DoctypeTest()
        {
            // TODO unit test for the property 'Doctype'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'Keyword'
        /// </summary>
        [Test]
        public void KeywordTest()
        {
            // TODO unit test for the property 'Keyword'
        }
        /// <summary>
        /// Test the property 'Other'
        /// </summary>
        [Test]
        public void OtherTest()
        {
            // TODO unit test for the property 'Other'
        }

    }

}
